name: Laravel CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job to run Laravel tests
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up PHP with Laravel
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, xml, bcmath, sqlite3, pdo, pdo_mysql

    # Install dependencies
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip
        curl -sS https://getcomposer.org/installer | php
        mv composer.phar /usr/local/bin/composer
        composer install --no-interaction

    # Set up environment variables (you can add more if needed)
    - name: Set up environment variables
      run: echo "APP_ENV=testing" >> .env

    # Run migrations and seed the database (use your testing database)
    - name: Run migrations
      run: |
        php artisan migrate --env=testing
        php artisan db:seed --env=testing

    # Run Laravel tests
    - name: Run Laravel tests
      run: |
        php artisan test

  # Job to run Postman collection tests
  postman:
    runs-on: ubuntu-latest
    needs: test  # Ensure that tests pass before running Postman tests

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Install Newman (CLI for Postman)
    - name: Install Newman
      run: npm install -g newman

    # Run Postman collection tests
    - name: Run Postman Collection Tests
      run: |
        newman run https://path_to_your_postman_collection.json -e https://path_to_your_postman_environment.json
