name: Laravel CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP 8.2
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, bcmath, sqlite3, pdo, pdo_mysql

    - name: Install Composer
      run: |
        cd backend
        curl -sS https://getcomposer.org/installer | php
        mv composer.phar /usr/local/bin/composer

    - name: Install dependencies
      run: |
        cd backend
        composer install --no-interaction

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Newman
      run: |
        npm install -g newman

    - name: Start Laravel server
      run: |
        cd backend
        php artisan serve --host=0.0.0.0 --port=8000 &
        sleep 5 # Ajusta el tiempo de espera si es necesario

    - name: Run migrations and seed database
      run: |
        cd backend
        php artisan migrate --env=testing
        php artisan db:seed --env=testing

    - name: Run Laravel tests
      run: |
        cd backend
        php artisan test --env=testing

    - name: Run Postman collection tests
      run: |
        cd backend
        newman run FlashFoods.postman_collection.json --env-var "BASE_URL=http://localhost:8000" --global-var "ENV=testing"
